MODEL:
    NAME: 'type-c'
    VERSION: 'v1'
    DESCRIPTION: 'MobileNetV1 model with l2 loss'
    CLASSES: []
    STRIDE: 8
    BACKBONE: 'mobilenet_v1'
    PRETRAIN: True


TRAIN:
    DATA_ROOT: 'data/type-c/train'
    IMG_INDEX: []
    IMG_SIZE: [256, 320]
    MEAN: [0.0, 0.0, 0.0]
    STD: [1.0, 1.0, 1.0]
    IMG_TYPE: 'png'
    SIGMA: 8
    DO_FLIP: False
    FLIP_PROB: 0.5
    DO_SCALE: True
    SCALE_RANGE: [0.8, 1.0]
    DO_ROTATE: True
    ROTATE_RANGE: [-5.0, 5.0]
    DO_ALBU: True
    ALBU_BRIGHTNESS: 0.5
    ALBU_CONTRAST: 0.5
    ALBU_SATURATION: 0.5
    ALBU_HUE: 0.0
    SIZE: 20


TEST:
    DATA_ROOT: 'data/type-c/test'
    IMG_INDEX: []
    IMG_SIZE: [256, 320]
    MEAN: [0.0, 0.0, 0.0]
    STD: [1.0, 1.0, 1.0]
    IMG_TYPE: 'png'
    SIZE: 20


DATALOADER:
    TRAIN:
        BATCH_SIZE: 4
        WORKERS: 0
    TEST:
        BATCH_SIZE: 8
        WORKERS: 0


SOLVER:
    EPOCHS: 200
    # loss function
    LOSS: 'l2'
    # optimizer
    OPT: 'adam'
    BASE_LR: 0.001
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
    # step
    GAMMA: 0.1
    STEPS: [60, 120, 180]
    # warm up
    WARMUP_FACTOR: 0.33
    WARMUP_ITERS: 6
    WARMUP_METHOD: 'linear'
    # log
    LOG_INTERVAL: 1
    # eval
    EVAL_EPOCH: 10
    # save model
    CHECKPOINT: 10

VISDOM:
    SHOW_LABEL: False
    SHOW_TRAIN_OUT: True
    SHOW_TEST_OUT: True
