MODEL:
    NAME: 'base'
    VERSION: 'v1'
    DESCRIPTION: 'MobileNetV1 model with l2 loss'
    CLASSES: []
    STRIDE: 8
    BACKBONE: 'mobilenet_v1'
    PRETRAIN: True
    CHECKPOINT: ''
    ANGLE: True
    SIZE: False


TRAIN:
    DATA_ROOT: 'data/base/train'
    IMG_INDEX: [1, 4, 8, 26]
    REPEAT_DATA: 4
    IMG_SIZE: [480, 640]
    MEAN: [0.0, 0.0, 0.0]
    STD: [1.0, 1.0, 1.0]
    IMG_TYPE: 'bmp'
    SIGMA: 8
    DO_FLIP: False
    FLIP_PROB: 0.5
    DO_SCALE: True
    SCALE_RANGE: [0.5, 1.5]
    DO_ROTATE: True
    ROTATE_RANGE: [-45.0, 45.0]
    DO_ALBU: True
    ALBU_BRIGHTNESS: 1.5
    ALBU_CONTRAST: 0.5
    ALBU_SATURATION: 0.5
    ALBU_HUE: 0.0
    SIZE: 20


TEST:
    DATA_ROOT: 'data/base/test'
    IMG_INDEX: []
    IMG_SIZE: [480, 640]
    MEAN: [0.0, 0.0, 0.0]
    STD: [1.0, 1.0, 1.0]
    IMG_TYPE: 'bmp'
    SIZE: 20


DATALOADER:
    TRAIN:
        BATCH_SIZE: 4
        WORKERS: 4
    TEST:
        BATCH_SIZE: 4
        WORKERS: 4


SOLVER:
    EPOCHS: 300
    # loss function
    LOSS: 'l2'
    # optimizer
    OPT: 'adam'
    BASE_LR: 0.0005
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
    # step
    GAMMA: 0.1
    # STEPS: [60, 120, 180]
    # STEPS: [120, 240, 360]
    STEPS: [120, 240]
    # warm up
    WARMUP_FACTOR: 0.33
    WARMUP_ITERS: 15
    WARMUP_METHOD: 'linear'
    # log
    LOG_INTERVAL: 1
    # eval
    EVAL_EPOCH: 10
    # save model
    CHECKPOINT: 50

VISDOM:
    SHOW_LABEL: False
    SHOW_TRAIN_OUT: False
    SHOW_LABEL_HEATMAP: False
    SHOW_TRAIN_HEATMAP: False
    SHOW_TEST_OUT: False
    SHOW_INFO: True
