MODEL:
    NAME: 'type-c'
    VERSION: 'v0'
    DESCRIPTION: 'Resnet34 model with MSELoss'
    CLASSES: []
    STRIDE: 4


TRAIN:
    DATA_ROOT: 'data/type-c/train'
    SIZE: [256, 320]
    MEAN: [0.152, 0.152, 0.152]
    STD: [0.251, 0.251, 0.251]
    IMG_TYPE: 'png'
    SIGMA: 5
    DO_FLIP: False
    FLIP_PROB: 0.5
    DO_SCALE: True
    SCALE_RANGE: [0.8, 1.0]
    DO_ROTATE: False
    ROTATE_RANGE: [-5.0, 5.0]


TEST:
    DATA_ROOT: 'data/type-c/test'
    SIZE: [256, 320]
    MEAN: [0.152, 0.152, 0.152]
    STD: [0.251, 0.251, 0.251]
    IMG_TYPE: 'png'


DATALOADER:
    TRAIN:
        BATCH_SIZE: 4
        WORKERS: 8
    TEST:
        BATCH_SIZE: 8
        WORKERS: 8


SOLVER:
    EPOCHS: 80
    # loss function
    LOSS: 'MSELoss'
    # optimizer
    OPT: 'adam'
    BASE_LR: 0.0005
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
    # step
    GAMMA: 0.1
    STEPS: [30, 60]
    # warm up
    WARMUP_FACTOR: 0.33
    WARMUP_ITERS: 6
    WARMUP_METHOD: 'linear'
    # log
    LOG_INTERVAL: 1
    # eval
    EVAL_EPOCH: 1
    # save model
    CHECKPOINT: 10

