MODEL:
    NAME: 'type-c'
    VERSION: 'v0'
    DESCRIPTION: 'Resnet34 model with MSELoss'
    CLASSES: []
    STRIDE: 4


TRAIN:
    DATA_ROOT: 'data/type-c/train'
    IMG_INDEX: []
    IMG_SIZE: [256, 320]
    MEAN: [0.177, 0.177, 0.177]
    STD: [0.151, 0.151, 0.151]
    IMG_TYPE: 'png'
    SIGMA: 8
    DO_FLIP: False
    FLIP_PROB: 0.5
    DO_SCALE: True
    SCALE_RANGE: [0.8, 1.0]
    DO_ROTATE: True
    ROTATE_RANGE: [-5.0, 5.0]
    DO_ALBU: True
    ALBU_BRIGHTNESS: 0.5
    ALBU_CONTRAST: 0.5
    ALBU_SATURATION: 0.5
    ALBU_HUE: 0.0
    SIZE: 20


TEST:
    DATA_ROOT: 'data/type-c/test'
    IMG_SIZE: [256, 320]
    MEAN: [0.177, 0.177, 0.177]
    STD: [0.151, 0.151, 0.151]
    IMG_TYPE: 'png'
    SIZE: 20


DATALOADER:
    TRAIN:
        BATCH_SIZE: 4
        WORKERS: 0
    TEST:
        BATCH_SIZE: 4
        WORKERS: 0


SOLVER:
    EPOCHS: 80
    # loss function
    LOSS: 'MSELoss'
    # optimizer
    OPT: 'adam'
    BASE_LR: 0.005
    # MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    # step
    GAMMA: 0.1
    STEPS: [30, 60]
    # warm up
    WARMUP_FACTOR: 0.33
    WARMUP_ITERS: 6
    WARMUP_METHOD: 'linear'
    # log
    LOG_INTERVAL: 1
    # eval
    EVAL_EPOCH: 10
    # save model
    CHECKPOINT: 10

