MODEL:
    NAME: 'base'
    VERSION: 'v0'
    DESCRIPTION: 'Resnet34 model with MSELoss'
    CLASSES: []
    STRIDE: 4
    BACKBONE: 'resnet34'
    PRETRAIN: True


TRAIN:
    DATA_ROOT: 'data/base/train'
    IMG_INDEX: [1, 4, 8 ,26]
    IMG_SIZE: [480, 640]
    MEAN: [0.177, 0.177, 0.177]
    STD: [0.151, 0.151, 0.151]
    IMG_TYPE: 'bmp'
    SIGMA: 10
    DO_FLIP: False
    FLIP_PROB: 0.5
    DO_SCALE: True
    SCALE_RANGE: [0.8, 1.0]
    DO_ROTATE: True
    ROTATE_RANGE: [-15.0, 15.0]
    DO_ALBU: True
    ALBU_BRIGHTNESS: 0.5
    ALBU_CONTRAST: 0.5
    ALBU_SATURATION: 0.5
    ALBU_HUE: 0.0
    SIZE: 20


TEST:
    DATA_ROOT: 'data/base/test'
    IMG_INDEX: []
    IMG_SIZE: [480, 640]
    MEAN: [0.177, 0.177, 0.177]
    STD: [0.151, 0.151, 0.151]
    IMG_TYPE: 'bmp'
    SIZE: 20


DATALOADER:
    TRAIN:
        BATCH_SIZE: 4
        WORKERS: 0
    TEST:
        BATCH_SIZE: 8
        WORKERS: 0


SOLVER:
    EPOCHS: 300
    # loss function
    LOSS: 'MSELoss'
    # optimizer
    OPT: 'adam'
    BASE_LR: 0.001
    # MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0001
    # step
    GAMMA: 0.1
    STEPS: [90, 180, 270]
    # warm up
    WARMUP_FACTOR: 0.33
    WARMUP_ITERS: 6
    WARMUP_METHOD: 'linear'
    # log
    LOG_INTERVAL: 1
    # eval
    EVAL_EPOCH: 10
    # save model
    CHECKPOINT: 10

